name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    if: "! contains(toJSON(github.event.commits.*.message), 'skip ci')"
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - name: Build the Docker image
      shell: bash
      run: |
        ./build.sh -d
