name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    if: "! contains(toJSON(github.event.commits.*.message), 'skip ci')"
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Build the Docker image
      shell: bash
      run: |
        ./build.sh
