name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    if: "! contains(toJSON(github.event.commits.*.message), 'skip ci')"
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Build the Docker image
      shell: bash
      run: |
        ./build.sh
